//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KAUSTConnectForm.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class Table_NewRequest
    {
		public int ID { get; set; }
		public string NewOrRenew { get; set; }
		[Required(ErrorMessage = "Please Select One")]
		public string EmailRequired { get; set; }
		public string ExistingUsername { get; set; }
		[Required(ErrorMessage = "First Name is Required")]
		[StringLength(50, ErrorMessage = "Maximum Length is 50")]
		public string FirstName { get; set; }
		public string MiddleName { get; set; }
		[Required(ErrorMessage = "Last Name is Required")]
		[StringLength(50, ErrorMessage = "Maximum Length is 50")]
		public string LastName { get; set; }
		[Required(ErrorMessage = "KAUST ID is Required")]
		[Range(100000, 999999, ErrorMessage = "Minimum and Maximum length is 6")]
		public Nullable<int> KAUSTID { get; set; }
		[Required(ErrorMessage = "Job Title is Required")]
		[StringLength(50, ErrorMessage = "Maximum Length is 50")]
		public string JobTitle { get; set; }
		[Required(ErrorMessage = "Vendor Name is Required")]
		[StringLength(50, ErrorMessage = "Maximum Length is 50")]
		public string VendorName { get; set; }
		[StringLength(50, ErrorMessage = "Maximum Length is 50")]
		public string NewEmail { get; set; }
		public string ExpiryDate { get; set; }
		public Nullable<long> PhoneNumber { get; set; }
		[Required(ErrorMessage = "Username is Required")]
		public string ReportingMngUsername { get; set; }
		public Nullable<int> ReportingMngKID { get; set; }
		[StringLength(50, ErrorMessage = "Maximum Length is 50")]
		public string ReportingMngName { get; set; }
		[StringLength(50, ErrorMessage = "Maximum Length is 50")]
		public string ReportingMngEmail { get; set; }
		[StringLength(50, ErrorMessage = "Maximum Length is 50")]
		public string LoginDetailsSentTo { get; set; }
		[Required(ErrorMessage = "Username is Required")]
		public string ManagerUsername { get; set; }
		[StringLength(50, ErrorMessage = "Maximum Length is 50")]
		public string ManagerName { get; set; }
		[StringLength(50, ErrorMessage = "Maximum Length is 50")]
		public string ManagerDept { get; set; }
		[StringLength(50, ErrorMessage = "Maximum Length is 50")]
		public string ManagerEmail { get; set; }
		public Nullable<int> ManagerKID { get; set; }
		public string ApprovedBy { get; set; }
		public string ApprovedOn { get; set; }
		public string MsgTeamApprovedBy { get; set; }
		public string MsgTeamApprovedOn { get; set; }
		public string Comments { get; set; }
		public string StatusOfRequest { get; set; }
		public string Requester { get; set; }
		public string RequesterEmail { get; set; }
		public byte[] IDimage { get; set; }
		[Required(ErrorMessage = "Email is Required")]
		[StringLength(50, ErrorMessage = "Maximum Length is 50")]
		public string Email { get; set; }
		[StringLength(50, ErrorMessage = "Maximum Length is 50")]
		public string ManagerTitle { get; set; }
		public string UserComments { get; set; }
	}
}
